
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MIVProject
{

using System;
    using System.Collections.Generic;
    
public partial class itemSubCategory
{

    public itemSubCategory()
    {

        this.item = new HashSet<item>();

    }


    public int subCategoryID { get; set; }

    public string name { get; set; }

    public int category { get; set; }



    public virtual ICollection<item> item { get; set; }

    public virtual itemCategory itemCategory { get; set; }

}

}
