//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIVProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mivEntities : DbContext
    {
        public mivEntities()
            : base("name=mivEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<criteria> criteria { get; set; }
        public virtual DbSet<currency> currency { get; set; }
        public virtual DbSet<deliveryMethod> deliveryMethod { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<itemCategory> itemCategory { get; set; }
        public virtual DbSet<itemSubCategory> itemSubCategory { get; set; }
        public virtual DbSet<mivUser> mivUser { get; set; }
        public virtual DbSet<paymentMethod> paymentMethod { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<projectItem> projectItem { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<supplierCategory> supplierCategory { get; set; }
        public virtual DbSet<supplyHeader> supplyHeader { get; set; }
        public virtual DbSet<supplyItem> supplyItem { get; set; }
        public virtual DbSet<supplyStatus> supplyStatus { get; set; }
        public virtual DbSet<userType> userType { get; set; }
    }
}
