//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIVProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.supplyHeader = new HashSet<supplyHeader>();
        }
    
        public int mivUser { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int category { get; set; }
        public string OIB { get; set; }
    
        public virtual mivUser mivUser1 { get; set; }
        public virtual supplierCategory supplierCategory { get; set; }
        public virtual ICollection<supplyHeader> supplyHeader { get; set; }
    }
}
