//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIVProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierCategory
    {
        public supplierCategory()
        {
            this.supplier = new HashSet<supplier>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<supplier> supplier { get; set; }
    }
}
